<a href="https://colab.research.google.com/github/Meghana09G/ICP2-WEEK-2-/blob/main/ICP_2_WEEK2_NEURAL.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# QUE 1

class Employee:
    # DATA MEMBER TO COUNT THE NUMBER OF EMPLOYEES
    empCount = 0

    # CONSTRUCTOR TO INITIALIZE NAME, FAMILY, SALARY, DEPARTMENT
    def __init__(self, name, family, salary, department):
        self.name = name
        self.family = family
        self.salary = salary
        self.department = department
        Employee.empCount += 1    # EMPLOYEE COUNT

    # FUNCTION FOR AVERAGE SALARY OF EMPLOYEE
    def avg_salary(self):
        total_salary = 0
        total_salary += float(self.salary)
        avg = total_salary / Employee.empCount
        print('Average salary of the Employee:', avg)

    # TO DISPLAY DETAILS OF EMPLOYEE
    def display(self):
        print('Employee Name:', self.name)
        print('Family Members:', self.family)
        print('Employee Annual Salary:', self.salary)
        print('Department:', self.department)
        print("==========")

# INHERITING - EMPLOYEE CLASS
class Fulltime_Employee(Employee):
    def __init__(self, name, family, salary, department, emp_type):
        Employee.__init__(self, name, family, salary, department)
        self.emp_type = emp_type

    #FUNCTION TO DISPLAY EMPLOYEE DETAILS
    def display(self):
        print("Employee Name :", self.name)
        print('Family Members:', self.family)
        print('Employee Annual Salary:', self.salary)
        print('Department:', self.department)
        print('Type of Employment :', self.emp_type)
        print("==========")


# INSTANCES FOR EMPLOYEE CLASS
emp1 = Employee('meghana', '4', '2100000', 'cloud architect')
# INSTANCE FOR FULL TIME EMPLOYEE
emp2 = Fulltime_Employee('saikrishna', '4', '2200000', 'cloud developer', 'Fulltime')
emp3 = Fulltime_Employee('shanthi', '3', '2500000', 'Power BI Developer', 'Fulltime')

print("Count of the Employees :", emp1.empCount)
emp1.avg_salary()
emp1.display()
emp2.display()
emp3.display()

Count of the Employees : 3
Average salary of the Employee: 700000.0
Employee Name: meghana
Family Members: 4
Employee Annual Salary: 2100000
Department: cloud architect
Employee Name : saikrishna
Family Members: 4
Employee Annual Salary: 2200000
Department: cloud developer
Type of Employment : Fulltime
Employee Name : shanthi
Family Members: 3
Employee Annual Salary: 2500000
Department: Power BI Developer
Type of Employment : Fulltime


https://drive.google.com/file/d/1gEKvKg8zKDeNurOM5QdvfaJWjd2lfbrN/view?usp=sharing

In [ ]:
# QUE 2

import numpy as np

# creating array of size as 20
random_vector = np.random.uniform(1, 20, 20)
print("Random Vector : \n", random_vector)

# reshape the array to 4 cross 5
random_vector = random_vector.reshape(4,5)
print("after reshaping (4 by 5): \n", random_vector)

# replace the maximum in each row
random_vector[np.arange(len(random_vector)), random_vector.argmax(1)] = 0
print("Replacing the maximum in each row : \n", random_vector)

Random Vector : 
 [13.634174   17.12339611 15.95000383 19.55050559  1.84113444 11.21404508
  9.41147996  7.45628214 18.02852999  2.23738545 19.90980639  3.25152467
 18.91794567 10.21001162 16.65711857 12.04996628 11.47551822  2.81517365
  6.29021525  9.93649888]
after reshaping (4 by 5): 
 [[13.634174   17.12339611 15.95000383 19.55050559  1.84113444]
 [11.21404508  9.41147996  7.45628214 18.02852999  2.23738545]
 [19.90980639  3.25152467 18.91794567 10.21001162 16.65711857]
 [12.04996628 11.47551822  2.81517365  6.29021525  9.93649888]]
Replacing the maximum in each row : 
 [[13.634174   17.12339611 15.95000383  0.          1.84113444]
 [11.21404508  9.41147996  7.45628214  0.          2.23738545]
 [ 0.          3.25152467 18.91794567 10.21001162 16.65711857]
 [ 0.         11.47551822  2.81517365  6.29021525  9.93649888]]


https://drive.google.com/file/d/1gEKvKg8zKDeNurOM5QdvfaJWjd2lfbrN/view?usp=sharing